version: 2.1

orbs:
  android: circleci/android@2.4.0
 
jobs:
  build:
    machine: 
        image: android:default
    resource_class: large
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Install and Set Java 17
          command: |
            sudo apt-get update
            sudo apt-get install -y openjdk-17-jdk
            echo 'export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64' >> $BASH_ENV
            echo 'export PATH=$JAVA_HOME/bin:$PATH' >> $BASH_ENV
            source $BASH_ENV
            java -version
      - run:
          name: Setup Android SDK and local.properties
          command: |
            echo "sdk.dir=$HOME/moriarty/android/sdk" > local.properties
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      
      # Code Style Check
      - run:
          name: Run Ktlint Check
          command: ./gradlew ktlintCheck
      
      # Build
      - run:
          name: Run Build
          command: ./gradlew build
      
      # Tests with Coverage
      - run:
          name: Run Tests with Coverage
          command: ./gradlew testDebugUnitTest jacocoTestReport
      
      # Regular Tests
      - run:
          name: Run Tests
          command: ./gradlew lint test
      
      # Install and Run Snyk
      - run:
          name: Install Snyk
          command: |
            sudo npm install -g snyk
            snyk auth $SNYK_TOKEN
      - run:
          name: Run Snyk Security Scan
          command: |
            snyk test --all-projects || true
            snyk monitor --all-projects || true
      
      # Store Results
      - store_artifacts: 
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:  
          path: app/build/outputs/apk/debug/
          destination: artifact-file
      - store_artifacts:
          path: app/build/reports/jacoco/jacocoTestReport
          destination: coverage-report