version: 2.1

orbs:
  android: circleci/android@0.2.1

executors:
  android-executor:
    docker:
      - image: cimg/android:2022.12
    working_directory: ~/code

jobs:
  build:
    executor: android-executor
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64  # Ensures JDK 17 is used
      PATH: "/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH"  # Updates PATH for Java commands
    steps:
      - checkout
      - restore_cache:
          key: android-orb-v1-
      - run:
          name: Verify JDK Version
          command: java -version
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
      - run:
          name: Run Code Style Check (Checkstyle)
          command: ./gradlew checkstyle
      - run:
          name: Run Build
          command: ./gradlew build
      - run:
          name: Run Lint Check
          command: ./gradlew lint
      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Generate Code Coverage Report
          command: ./gradlew jacocoTestReport
      - run:
          name: Analyze Dependencies for Vulnerabilities
          command: ./gradlew dependencyCheckAnalyze
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_artifacts:
          path: app/build/reports/checkstyle
          destination: checkstyle-reports
      - store_artifacts:
          path: app/build/reports/lint-results.html
          destination: lint-reports
      - store_artifacts:
          path: app/build/reports/jacoco/test/html
          destination: code-coverage-reports
      - store_test_results:
          path: app/build/test-results
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: apks

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
