version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    executor: android/android
    environment:
      JAVA_HOME: /usr/lib/jvm/java-17-openjdk-amd64
      PATH: "/usr/lib/jvm/java-17-openjdk-amd64/bin:$PATH"
    steps:
      # Add SSH installation step
      - run:
          name: Install SSH client
          command: |
            sudo apt-get update
            sudo apt-get install -y openssh-client
      
      # Checkout with HTTPS instead of SSH
      - checkout:
          path: .
      
      - restore_cache:
          key: android-orb-v1-
          
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
          
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
          
      - save_cache:
          key: 'android-orb-v1-{{ epoch }}'
          paths:
            - ~/.android/build-cache
            - ~/.android/cache
            
      - run:
          name: Run Build
          command: ./gradlew build
          
      - store_artifacts:
          path: app/build/reports
          destination: reports
          
      - run:
          name: Run Tests
          command: ./gradlew lint test
          
      - store_test_results:
          path: app/build/test-results
          
      - store_artifacts:
          path: app/build/outputs/apk/debug/
          destination: artifact-file

workflows:
  version: 2
  build:
    jobs:
      - build